name: Run all tests

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      # Integration tests are not yet ready to run in parallel
      max-parallel: 1
      matrix:
        node: ['10', '12', '14']

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - run: yarn
      - run: npm run lint
      - run: npm test
        env:
          TRANSLOADIT_KEY: ${{ secrets.TRANSLOADIT_KEY }}
          TRANSLOADIT_SECRET: ${{ secrets.TRANSLOADIT_SECRET }}

      - run: echo "COVERAGE_PERCENT=$(npm run --silent get-coverage-percent)" >> $GITHUB_ENV

      - uses: schneegans/dynamic-badges-action@v1.0.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: f8a10961b85300969759bc0b367fa77a
          filename: badge.json
          label: coverage
          message: ${{ env.COVERAGE_PERCENT }}
          color: brightgreen
